### ISSUE TITLE
ModuleNotFoundError in version 0.1.8

### ISSUE THREAD

**Issue by VDhriti** [commit-0/commit0#99]
Traceback (most recent call last):
  File "/home/dverma1/nlp/test2/.venv/bin/agent", line 5, in <module>
    from agent.__main__ import main
  File "/home/dverma1/nlp/test2/.venv/lib/python3.12/site-packages/agent/__main__.py", line 1, in <module>
    from agent.cli import agent_app
  File "/home/dverma1/nlp/test2/.venv/lib/python3.12/site-packages/agent/cli.py", line 2, in <module>
    from agent.run_agent_no_rich import run_agent as run_agent_no_rich
  File "/home/dverma1/nlp/test2/.venv/lib/python3.12/site-packages/agent/run_agent_no_rich.py", line 7, in <module>
    from agent.agent_utils import (
  File "/home/dverma1/nlp/test2/.venv/lib/python3.12/site-packages/agent/agent_utils.py", line 8, in <module>
    import fitz
ModuleNotFoundError: No module named 'fitz'

Commands run (terminal history):

  295  mkdir test2
  296  cd test2
  297  python3.12 -m venv .venv
  298  source .venv/bin/activate
  299  ls
  300  git clone https://github.com/commit-0/commit0.git
  301  pip install git+https://github.com/commit-0/commit0
  302  ls
  303  mkdir testing_env
  304  cd testing_env/
  305  ls
  306  commit0 setup parsel
  307  agent config aider

**Comment by wenting-zhao** [comment]
oh sorry. to install agent you will need `pip install commit0[agent]`
